#!/bin/bash
STUDENT_NAME="Aman Kumar"
SOFTWARE_CHOICE="Python"
DISTRO="Windows (Git Bash)"
echo "==========================================="
echo "        The Open Source Audit              "
echo "==========================================="
echo "Auditor : $STUDENT_NAME"
echo "Software: $SOFTWARE_CHOICE"
echo "-------------------------------------------"
echo "OS/Distro: $DISTRO"
echo "Kernel   : $(uname -r)"
echo "User     : $(whoami)"
echo "Date     : $(date)"
echo "==========================================="
